### ISSUE TITLE
Table layout breaks when a value is multiline

### ISSUE THREAD

**Issue by gairadzi** [Evertras/bubble-table#51]
If the value of one the columns includes a newline character (and the string before it is smaller than the column's max width) the table  layout will break.

This can be reproduced by changing the value in line 28 of `examples/simplest/main.go`  to `Electric\nhello`

This is because the rune width of the first line is smaller than the max width, I believe the expected behavior should be to only show the first line appended by the dots (to indicate it includes further data).

**Comment by Evertras** [comment]
Initially addressed by #52  (linking here for tracking) but still missing one issue.

Turns out this still breaks in an edge case:

<img width="458" alt="image" src="https://user-images.githubusercontent.com/5923958/158059926-d79bc25b-6c27-455a-b86a-cab105d7fc3b.png">

If the first line is *exactly* the max length, adding the `...` character at the end makes it too long.

**Comment by Evertras** [comment]
Latest PR should fix this

**Comment by Evertras** [comment]
Released `v0.8.4`, let me know if this looks good to you and then feel free to close the issue.  Thanks again for the contribution!

**Comment by gairadzi** [comment]
Looks great, thanks!
