### ISSUE TITLE
FlexColumn not showing anything

### ISSUE THREAD

**Issue by Robert-M-Muench** [Evertras/bubble-table#58]
With
```go
a.lt.licsTable = table.New(
[]table.Column{
	table.NewColumn(tcEmail, "Email", 20),
	table.NewColumn(tcEnd, "End", 20),
	table.NewColumn(tcPaidUntil, "Paid Until", 20),
	table.NewColumn(tcVersion, "Version", 20),
}).WithPageSize(10).SortByDesc(tcPaidUntil).WithRows(generateRows(a.lt))
```
I get:
<img width="685" alt="Ohne Titel 3" src="https://user-images.githubusercontent.com/1826391/163230238-613f1c8c-c03f-499f-8037-2825a29fe851.png">

But, with:
```go
a.lt.licsTable = table.New(
[]table.Column{
	table.NewFlexColumn(tcEmail, "Email", 1),
	table.NewColumn(tcEnd, "End", 20),
	table.NewColumn(tcPaidUntil, "Paid Until", 20),
	table.NewColumn(tcVersion, "Version", 20),
}).WithPageSize(10).SortByDesc(tcPaidUntil).WithRows(generateRows(a.lt))
```
I get:
<img width="536" alt="image" src="https://user-images.githubusercontent.com/1826391/163229502-03a88730-9dc6-4159-99ff-de20226dd559.png">

Is there anything special I need to take care of when using flex columns?

**Comment by Evertras** [comment]
You'll need to use [`WithTargetWidth`](https://pkg.go.dev/github.com/evertras/bubble-table/table#Model.WithTargetWidth).  I'll add a comment in the flex column example to better explain this.

**Comment by Evertras** [comment]
I've added [this comment in the example](https://github.com/Evertras/bubble-table/blob/main/examples/flex/main.go#L30) to better explain the requirement of `WithTargetWidth`, as well as updated the [actual doc comment](https://github.com/Evertras/bubble-table/blob/main/table/column.go#L34-L36) which will update on godocs in the near future when it refreshes.

If you think this is insufficient or there's still an issue with flex columns, let me know, otherwise feel free to close this issue if things are working properly for you.
